@startuml
skinparam componentStyle rectangle
actor user
user -down-> [CLIverShelf]
[CLIverShelf] -down-> [Logic]
[Logic] -down-> [Model]
[Storage] --> [Model]
[CLIverShelf] -right-> [UI]
[CLIverShelf] -left-> [Storage]
@enduml