@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml

actor user
participant ":Parser" as Parser PARSER_COLOR
participant Main MAIN_COLOR

user -> Main: Run program & Input commands
Main -> Parser: parseCommand(input, warehouse)
Parser --> Main: Command
Main -> "{action}Command": execute(warehouse)
"{action}Command" --> Main: resultString
Main -> UI: printMessageBubble(resultString)

@enduml