@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml


participant ":CliverShelf" as Main
participant "newCommand:AddCommand" as AddCommand
participant "newItem:Item" as Item
participant ":ShelfList" as ShelfList
participant "specifiedShelf:Shelf" as Shelf


Main -> AddCommand: execute()
activate AddCommand
AddCommand -> Item **
activate Item
Item --> AddCommand : newItem
deactivate Item
AddCommand -> ShelfList: getShelf(shelfName)
AddCommand -> Shelf: addItem(newItem)
AddCommand --> Main: finishedMessage
deactivate AddCommand

destroy AddCommand


@enduml