@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml

participant ":CliverShelf" as Main
participant ":Parser" as Parser
participant "newCommand:Command" as Command


Main -> Parser: parseCommand(input)
activate Parser
Parser -> Parser: prepareCommand(input)
activate Parser
Parser -> Command **: new Command(arguments)

activate Command
Command --> Parser: newCommand
deactivate Command
Parser --> Parser: newCommand
deactivate Parser
Parser --> Main: newCommand
deactivate Parser

Main -> Command: execute()
activate Command


Command --> Main
deactivate Command
deactivate Command
destroy Command

@enduml