@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml

actor user
participant ":CLIverShelf" as app LOGIC_COLOR
participant "newCommand:\nListCommand" as listCommand LOGIC_COLOR_T2
participant "specifiedShelf:\nShelf" as Shelf
user -> app: input
activate app


app -> listCommand: execute()


activate listCommand
alt !printAll
    listCommand -> listCommand : getOneList(shelfName)
    activate listCommand
    listCommand -> Shelf : createOutput()
    activate Shelf
    Shelf --> listCommand : shelfInfo
    deactivate Shelf
    listCommand --> listCommand :output
    deactivate listCommand


else printAll
    loop for every shelf in shelves
        listCommand -> listCommand : getOneList(shelf.getName())
        activate listCommand
        listCommand -> Shelf : createOutput()
        activate Shelf
        Shelf --> listCommand : shelfInfo
        deactivate Shelf
        listCommand --> listCommand : output
        deactivate listCommand
    end

end

listCommand --> app
deactivate listCommand
destroy listCommand
app --> user
deactivate app

hide footbox
@enduml