@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml

actor user

participant CLIverShelf as app LOGIC_COLOR
participant ":Parser" as parser LOGIC_COLOR_T1
participant ":newCommand: MarkUpCommand" as markupCommand MARKUP_COMMAND_COLOUR
participant ":SalesMarkUp" as SalesMarkUp SALES_MARKUP_COLOUR

user -> app: input
activate app
app -> parser: parseCommand(input)
activate parser
parser -> parser : prepareMarkup(argument)
activate parser
parser -> markupCommand **
deactivate parser
activate markupCommand
markupCommand --> parser

deactivate markupCommand
parser --> app
deactivate parser

app -> markupCommand: execute()

activate markupCommand
alt shelfName == soldItems
    markupCommand --> app : MARKUP_ON_SOLDITEMS_NOT_PERMITTED_MESSAGE
end

markupCommand -> SalesMarkUp ** : new SalesMarkUp(shelfName, index, userRequestPercent)
activate SalesMarkUp
SalesMarkUp --> markupCommand
deactivate SalesMarkUp

markupCommand -> SalesMarkUp : getItemToMarkUpInfo()
activate SalesMarkUp
SalesMarkUp --> markupCommand : itemMarkUpInfoString
deactivate SalesMarkUp

markupCommand -> SalesMarkUp : getSelectedItemMarkUpInfo()
activate SalesMarkUp
SalesMarkUp --> markupCommand : selectedItemMarkUpInfoString
deactivate SalesMarkUp

alt userRequestPercent == ""
    markupCommand -> SalesMarkUp : getEstimatedMarkUpInfo()
    activate SalesMarkUp
    SalesMarkUp --> markupCommand : estimatedMarkUpInfoString
    deactivate SalesMarkUp
else
   markupCommand -> SalesMarkUp : getUserRequestMarkUpInfo()
       activate SalesMarkUp
       SalesMarkUp --> markupCommand : userRequestMarkUpInfoString
       deactivate SalesMarkUp
end

markupCommand --> app : resultString
deactivate markupCommand
app --> user
deactivate app

hide footbox

@enduml