@startuml
!include Style.puml

participant ":Command" as command
participant "shelfList:ShelfList" as shelfList
participant "novel-1:Shelf" as shelf
command -> shelfList: addShelf("novel-1")
activate shelfList
shelfList -> shelf**
activate shelf
shelf -> shelfList:addShelf(this)
activate shelfList
shelfList --> shelf
deactivate
shelf --> shelfList: novel-1
deactivate
shelfList --> command: novel-1
deactivate
@enduml