@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml
actor user

participant CliverShelf as app
participant ":Parser" as parser
participant ":{commandWord}Command" as newCommand

user -> app: input
activate app
app -> parser: parseCommand(input)
activate parser
parser -> parser : prepare{commandWord}(argument)
activate parser
parser -> newCommand **
activate newCommand
newCommand --> parser
deactivate newCommand

parser --> parser : new {commandWord}Command

deactivate parser

parser --> app : {commandWord}Command
deactivate parser
app --> user
deactivate app

@enduml