@startuml
'https://plantuml.com/sequence-diagram
!include Style.puml
actor user

participant CLIverShelf as app LOGIC_COLOR
participant ":Parser" as parser LOGIC_COLOR_T1
participant ":{commandWord}Command" as newCommand MARKUP_COMMAND_COLOUR

user -> app: input
activate app
app -> parser: parseCommand(input)
activate parser
parser -> parser : prepare{commandWord}(argument)
activate parser
parser -> newCommand **
deactivate parser
activate newCommand
newCommand --> parser
deactivate newCommand
parser --> app : {commandWord}Command
deactivate parser
app --> user
deactivate app

@enduml