@startuml
'https://plantuml.com/class-diagram
!include Style.puml
hide circle
skinparam classAttributeIconSize 0
hide empty members

class Clivershelf{
}

class SalesManager{
}

class SalesReport{
}

class SalesMarkUp{
}

class SellCommand{
}

class MarkUpCommand{
}

class ReportCommand{
}

Clivershelf -- ReportCommand : executes >
Clivershelf -- MarkUpCommand : executes >
Clivershelf -- SellCommand : executes >

ReportCommand --> SalesReport
SalesReport --> SalesManager
MarkUpCommand --> SalesMarkUp
SellCommand --> SalesManager

@enduml