@startuml
'https://plantuml.com/class-diagram
!include Style.puml
hide circle

class Parser{
    + parseCommands() : Command
}

class SalesManager{
    + {static} getSalesManager():SalesManager
    + sell(item:Item):SoldItem
    + filterSoldItems(selectedStartDate:String, selectedEndDate:String):ArrayList<SoldItem>
}

class SalesReport{
    + SalesReport(selectedDate:String, selectedEndDate:String)
    + generateSoldItemStats():String
    + generateSoldItemDetails():String
}

class SalesMarkUp{
    + getItemToMarkUpInfo():String
    + getSelectedItemMarkUpInfo():String
    + getUserRequestMarkUpInfo():String
    + getEstimatedMarkUpInfo():String
}

class SellCommand{
    + SellCommand(String itemID)
    + execute() : String
}

class MarkUpCommand{
    + MarkUpCommand(shelfName:String, index:String, userRequestPercent:String)
    + execute() : String
}

class ReportCommand{
    + ReportCommand(selectedStartDate:String, selectedEndDate:String, reportType:String)
    + execute() : String
}

Parser --> ReportCommand
Parser --> MarkUpCommand
Parser --> SellCommand

ReportCommand --> SalesReport
SalesReport --> SalesManager
MarkUpCommand --> SalesMarkUp
SellCommand --> SalesManager

@enduml